# Generated by Django 4.2.2 on 2023-09-20 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planApi', '0002_prehabtrainingplan_gymtrainingplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrehabTrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equipment_used', models.CharField(max_length=100)),
                ('rest', models.CharField(max_length=100)),
                ('sets', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='planApi.prehabtrainingplan')),
            ],
        ),
        migrations.CreateModel(
            name='GymTrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('equipment_used', models.CharField(max_length=100)),
                ('rest', models.CharField(max_length=100)),
                ('sets', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='planApi.gymtrainingplan')),
            ],
        ),
    ]
