# Generated by Django 4.2.2 on 2023-10-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planApi', '0007_alter_healthmarkerstest_vo2_max'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitreachtest',
            old_name='measurement',
            new_name='first_measurement',
        ),
        migrations.AddField(
            model_name='sitreachtest',
            name='second_measurement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sitreachtest',
            name='third_measurement',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
