# Generated by Django 4.2.2 on 2023-10-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planApi', '0010_fingerstrengthtest_left_fingerstrengthtest_right_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maxpullupstest',
            old_name='seconds',
            new_name='reps',
        ),
    ]
