# Generated by Django 4.2.2 on 2023-10-02 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_healthmarkerstest_delete_healthmarkertest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthmarkerstest",
            name="marker",
        ),
    ]
