# Generated by Django 4.2.2 on 2023-10-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0006_remove_healthmarkerstest_marker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthmarkerstest",
            name="vo2_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
