# Generated by Django 4.2.2 on 2023-10-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0009_pushuptest_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="fingerstrengthtest",
            name="left",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="fingerstrengthtest",
            name="right",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="maxlockofftest",
            name="seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="maxpullupstest",
            name="seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="oafingerstrengthtest",
            name="left",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="oafingerstrengthtest",
            name="left_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="oafingerstrengthtest",
            name="right",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="oafingerstrengthtest",
            name="right_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="oapinchtest",
            name="left",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="oapinchtest",
            name="right",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="powerendurancetest",
            name="seconds",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="fingerstrengthtest",
            name="test",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="maxlockofftest",
            name="test",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="maxpullupstest",
            name="test",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="oafingerstrengthtest",
            name="test",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="oapinchtest",
            name="test",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="powerendurancetest",
            name="test",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
