# Generated by Django 4.2.2 on 2023-10-24 20:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_rename_seconds_maxpullupstest_reps"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fingerstrengthtest",
            old_name="left",
            new_name="percentage_bodyweight",
        ),
        migrations.RenameField(
            model_name="fingerstrengthtest",
            old_name="right",
            new_name="total_load",
        ),
    ]
