# Generated by Django 4.2.2 on 2023-11-06 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0013_remove_fingerstrengthtest_test_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clientavailability",
            name="created",
        ),
        migrations.RemoveField(
            model_name="clientavailability",
            name="friday",
        ),
        migrations.RemoveField(
            model_name="clientavailability",
            name="monday",
        ),
        migrations.RemoveField(
            model_name="clientavailability",
            name="saturday",
        ),
        migrations.RemoveField(
            model_name="clientavailability",
            name="sunday",
        ),
        migrations.RemoveField(
            model_name="clientavailability",
            name="thursday",
        ),
        migrations.RemoveField(
            model_name="clientavailability",
            name="trainee",
        ),
        migrations.RemoveField(
            model_name="clientavailability",
            name="tuesday",
        ),
        migrations.RemoveField(
            model_name="clientavailability",
            name="updated",
        ),
        migrations.RemoveField(
            model_name="clientavailability",
            name="wednesday",
        ),
        migrations.AddField(
            model_name="clientavailability",
            name="client",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability",
                to="common.generalclientinfo",
            ),
        ),
        migrations.AddField(
            model_name="dayavailability",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="common.generalclientinfo",
            ),
        ),
        migrations.AddField(
            model_name="dayavailability",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dayavailability",
            name="day",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="dayavailability",
            name="slots",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="dayavailability",
            unique_together={("client", "day")},
        ),
    ]
