# Generated by Django 4.2.2 on 2023-11-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_remove_clientavailability_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalclientinfo',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
