# Generated by Django 4.2.2 on 2023-11-07 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_generalclientinfo_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientequipment',
            name='equipment',
        ),
        migrations.AddField(
            model_name='clientequipment',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='client_equipment', to='common.equipment'),
        ),
    ]
