# Generated by Django 4.2.2 on 2023-11-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_remove_clientequipment_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprograminfo',
            name='payment_rate',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
