# Generated by Django 4.2.2 on 2023-11-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_alter_clientprograminfo_payment_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fingerstrengthtest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='maxlockofftest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='maxpullupstest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='oafingerstrengthtest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='oapinchtest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='powerendurancetest',
            name='assessment',
        ),
    ]
