# Generated by Django 4.2.2 on 2023-11-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_remove_fingerstrengthtest_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerstrengthtest',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='common.fingerstrengthassessments'),
        ),
        migrations.AddField(
            model_name='maxlockofftest',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='common.maxlockoffassessments'),
        ),
        migrations.AddField(
            model_name='maxpullupstest',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='common.maxpullupsassessments'),
        ),
        migrations.AddField(
            model_name='oafingerstrengthtest',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='common.oafingerstrengthassessments'),
        ),
        migrations.AddField(
            model_name='oapinchtest',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='common.oapinchassessments'),
        ),
        migrations.AddField(
            model_name='powerendurancetest',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='common.powerenduranceassessments'),
        ),
    ]
