# Generated by Django 4.2.2 on 2023-11-08 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_climbingassessments_fitnessassessments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessassessments',
            name='trainee',
        ),
        migrations.RemoveField(
            model_name='coretest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='daviestest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='fingerstrengthtest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='healthmarkerstest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='maxlockofftest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='maxpullupstest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='measurementstest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='oafingerstrengthtest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='oapinchtest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='overheadsquattest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='powerendurancetest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='pushuptest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='sharkskillstest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='sitreachtest',
            name='assessment',
        ),
        migrations.RemoveField(
            model_name='ymcasteptest',
            name='assessment',
        ),
        migrations.DeleteModel(
            name='ClimbingAssessments',
        ),
        migrations.DeleteModel(
            name='FitnessAssessments',
        ),
    ]
