from rest_framework.serializers import ModelSerializer
from .models.training_models import (
    OTWTrainingPlan,
    TrainingExercise,
    GymTrainingPlan,
    GymTrainingExercise,
    PrehabTrainingExercise,
    PrehabTrainingPlan,
)
from .models.fitness_models import (
    HealthMarkersAssessments,
    HealthMarkersTest,
    MeasurementsAssessments,
    MeasurementsTest,
    OverheadSquatAssessments,
    OverheadSquatTest,
    YMCAStepAssessments,
    YMCAStepTest,
    SitReachAssessments,
    SitReachTest,
    PushUpAssessments,
    PushUpTest,
    DaviesAssessments,
    DaviesTest,
    SharkSkillsAssessments,
    SharkSkillsTest,
    SharkSkillsSide,
    CoreAssessments,
    CoreTest,
)
