# Generated by Django 4.2.2 on 2023-10-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_real',
            field=models.BooleanField(default=False),
        ),
    ]
