# Generated by Django 4.2.2 on 2023-10-25 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_real'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_real',
        ),
    ]
